<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="SIPSorcery" Version="10.0.3" />
    <PackageVersion Include="SIPSorceryMedia.Abstractions" Version="10.0.13" />
    <PackageVersion Include="SIPSorceryMedia.Windows" Version="10.0.13" />
    <PackageVersion Include="SIPSorceryMedia.Encoders" Version="10.0.4" />
    <PackageVersion Include="TUnit" Version="1.44.39" />
  </ItemGroup>
</Project>
